# settings.py

BOT_NAME = "yahoo_scraper"
SPIDER_MODULES = ["yahoo_scraper.spiders"]
NEWSPIDER_MODULE = "yahoo_scraper.spiders"

# --- 1. RESSEMBLER À UN HUMAIN ---
# Utilisation d'un User-Agent récent et standard
USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"

# --- 2. GESTION DES COOKIES (CRUCIAL POUR YAHOO) ---
COOKIES_ENABLED = True
COOKIES_DEBUG = False  # Mettre à False pour éviter de polluer les logs, sauf si ça plante

# Votre chaîne de cookies extraite (Formatée pour éviter les erreurs de syntaxe)
# Note : Si le scraping échoue dans quelques jours, c'est que ce cookie a expiré.
YAHOO_COOKIES = (
    '__eoi=ID=03f5c7e1c52913ed:T=1764600785:RT=1764600785:S=AA-AfjagUxvN1O87lFCVVM8xdHRY; '
    '__gpi=UID=00001316aabad954:T=1764600785:RT=1764600785:S=ALNI_MYbghjgyhaAx00OwMdT3OWhtPzcqg; '
    'axids=gam=y-iV55s4tE2uIWZQA9W8W69jpMYAdoAhLF~A&dv360=eS1GSmtXQmVsRTJ1RnNqTXRQSVlFek5VRXNGTy5sOUdZTn5B&ydsp=y-FT3_NPRE2uKJ0250iYflhMoFvvPiskNy~A&tbla=y-Gk4Wj9VE2uL.a0yzURybB4ZhJm92lPjl~A; '
    'tbla_id=56066aab-b292-4df4-8ce5-d3352cc9ba74-tuctfe8c556; '
    '_ga=GA1.1.1821689049.1760509910; '
    '_ga_YD9K1W9DLN=GS2.1.s1764596780$o6$g1$t1764600196$j56$l0$h0; '
    '_ebd=YmlkLTA4cmFmZHRraXI4M3UmZD00ZmE4N2FkNDlmNjUwMzgxYWYwMDc2MDQzZWU4ZDdhZiZ2PTE=; '
    'A1S=d=AQABBDqhLWkCEHZzavPDvAGOalrFjG9CNUsFEgABCAHxLmlfaeWnJm0A9qMCAAcIfqAtaW9PbQQ&S=AQAAAoCKAJYmY-yjEG0AOGzJaVk; '
    'EuConsent=CQbwIkAQbwIkAAOACBFRCGFoAP_gAEPgACiQKptB9G7eTXFneTJ2YPskOYwX0VBJ4MAwBgCBAUABzBIUIBwGVmAzJEyIICACGAIAIGBBIABtGAhAQEAAIIAVAABIAEgAIBAAIGAAACAAQABACAAAAAAAAAAQgEAXMBQgmCYEBFoIQUhAggAgAQAAAAAEAIgBCAQAEAAAQAAACAAAACgAggAAAAAAAAAEAFAIEQAAIAECAgPkdAAAAAAAAAAIAAYACEABAAAAAIKpgAkGhUQRFgQABAIGEECAAQUBABQIAgAACBAAAATBAUIAwAVGAyAEAIAAAAAAAAAAABAAABAAhAAEAAAIAQAAAIAAgAIAAAACAAAAAAQAAAAAAAAAAAAAAAAAAGIBAggCAABBAAQUAAAAAgAAAAAAAAAIgACAAAAAAAAAAAAAAAgAAAgAAAAAAAAAAAAAAIEQAAIAAAAoDEFgAAAAAAAAAAAAAACEABAAAAAIAAA; '
    'GUC=AQABCAFpLvFpX0IfiQSg&s=AQAAALQ7uw7r&g=aS2hRA; '
    'cmp=t=1764597588&j=1&u=1---&v=107; '
    '_ga_BFY40XXE01=GS2.1.s1762781827$o1$g1$t1762782093$j26$l0$h0; '
    '_ga_C5QRNK12P6=GS2.1.s1762782065$o1$g0$t1762782067$j58$l0$h0; '
    'PRF=t%3DAPI%252BORSTED.CO; '
    '_dmieu=CQaq64AQaq64AAOABBENCEFoAP_gAEPgACiQKZNB9G7WTWFjeTJ2YPskOYwH0VBJ4MAwBgCBAUABzBIUIBwGRmAxJAyIICACGAIAIGBBIABlGABAQEAAIIAFAABIAEgAIBAAICAAAAAAAABACAAAAAAAAAAQgEAVMBQgmAYEBFoIQUhAggAAAQAAAAAEAIABAAQAAAAAQAAACAAAACgAAgAAAAAAAAAEAFAIAAAAIAECAgMkdAAAAAAAAAAIAAYAAAABBVMAEg0KiCIsiAAIBAwggQACCgIAKBAEAAAQIAAACYIChAGACowGQAgBAAAAAAAAAAAAIAABIAEIAAgAABAAAAABAAEABAAAAAwAAAQAAAAAAAAAAAAAAAAAAAAAxAIEEAQAAIIACCgAAAAEAAAAAAAAABEAAQAAAgAAAAAAAAAAEAAAAAAAAAAAAAAAAAABAgAABAAAAFAYgsAAAAAAAAAAAAAAAQAAIAAAABAA.YAAAAAAAEJTgAAAAAAAAAAAA; '
    '_dmit=BGabf2QtVaDOjIekX4IhS6EGrMtD0GrMtD6DVmWkhAFAIgqACAAAAAAAAAAAAAAAAAAAAAiAAEAABNoQHkAAiAAA.bid-0ic6d5tke9evo.eyJvIjoiYmlkLTBpYzZkNXRrZTlldm8ifQ==.1762781929998~AMEQCIBX85FL2pzClVwwy23zHy/PnEx4UE1rOgCaHCBNKlAg/AiBESJ5IEwjzGUsrlTz6e46Kb8maVuQ/v6pvvJcDgG3VCA=='
)

DEFAULT_REQUEST_HEADERS = {
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
    'Accept-Language': 'fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7',
    'User-Agent': USER_AGENT,
    'Cookie': YAHOO_COOKIES, # Injection du cookie ici
    'Cache-Control': 'no-cache',
    'Pragma': 'no-cache',
}

# --- 3. COMPORTEMENT DU ROBOT ---
ROBOTSTXT_OBEY = False # Indispensable pour Yahoo Finance

DOWNLOAD_DELAY = 1.5 # Augmenté légèrement pour être plus sûr
RANDOMIZE_DOWNLOAD_DELAY = True # Ajoute une variation aléatoire (entre 0.75s et 2.25s)

CONCURRENT_REQUESTS = 4
CONCURRENT_REQUESTS_PER_DOMAIN = 2 # On ralentit spécifiquement sur le domaine pour éviter le ban

# --- 4. CONFIGURATION TECHNIQUE ---
REQUEST_FINGERPRINTER_IMPLEMENTATION = "2.7"
TWISTED_REACTOR = "twisted.internet.asyncioreactor.AsyncioSelectorReactor"
FEED_EXPORT_ENCODING = "utf-8"
LOG_LEVEL = "INFO"

# Gestion des redirections (Yahoo aime utiliser Meta Refresh pour bloquer)
REDIRECT_ENABLED = True
METAREFRESH_ENABLED = True